apiVersion: v1
kind: ConfigMap
metadata:
    name: ixiatg-release-config
    namespace: ixiatg-op-system
data:
    versions: |
        {
        "release": "local",
        "images": [
                {
                    "name": "controller",
                    "path": "ghcr.io/open-traffic-generator/licensed/ixia-c-controller",
                    "tag": "0.0.1-3807"
                },
                {
                    "name": "gnmi-server",
                    "path": "ghcr.io/open-traffic-generator/ixia-c-gnmi-server",
                    "tag": "1.10.14"
                },
                {
                    "name": "traffic-engine",
                    "path": "ghcr.io/open-traffic-generator/ixia-c-traffic-engine",
                    "tag": "1.6.0.30"
                },
                {
                    "name": "protocol-engine",
                    "path": "ghcr.io/open-traffic-generator/licensed/ixia-c-protocol-engine",
                    "tag": "1.00.0.271"
                },
                {
                    "name": "controller-community",
                    "path": "ghcr.io/open-traffic-generator/ixia-c-controller",
                    "tag": "1.00.0.271"
                },
                {
                    "name": "ixia-c-one",
                    "path": "ghcr.io/open-traffic-generator/ixia-c-one",
                    "tag": "0.0.1-3807"
                }
            ]
        }
