name: Free CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Setup docker
        uses: docker-practice/actions-setup-docker@master
      - name: Deploy back-to-back free distribution of ixia-c
        run: |
          ./do.sh topo new
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"
      - name: Run go tests
        run: |
          ./do.sh pregotest
          ./do.sh gotest -tags=free
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Run python tests
        run: |
          ./do.sh prepytest
          ./do.sh pytest -m free
      - name: Get container logs
        run: |
          ./do.sh topo logs
      - name: Archive logs
        uses: actions/upload-artifact@v2
        with:
          name: generated-artifacts
          path: |
            logs
      - name: Teardown back-to-back free distribution of ixia-c
        run: |
          ./do.sh topo rm
