name: Perf CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Setup docker
        uses: docker-practice/actions-setup-docker@5d9a5f6
      - name: Deploy back-to-back licensed distribution of ixia-c
        run: |
          GITHUB_USER=${{ secrets.ENV_GITHUB_USER }} GITHUB_PAT=${{ secrets.ENV_GITHUB_PAT }} ./do.sh topo new lic
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"
      - name: Run go tests (HTTP)
        run: |
          ./do.sh pregotest
          OTG_ITERATIONS=10 ./do.sh gotest -tags=perf
      - name: Run go tests (gRPC)
        run: |
          ./do.sh pregotest
          OTG_ITERATIONS=10 OTG_GRPC_TRANSPORT=true OTG_HOST="$(grep otg_host test-config.yaml | cut -d/ -f3):40051" ./do.sh gotest -tags=perf
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Run python tests
        run: |
          ./do.sh prepytest
          OTG_ITERATIONS=2 ./do.sh pytest -m perf
      - name: Get container logs
        if: always()
        run: |
          ./do.sh topo logs lic
      - name: Archive logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: generated-artifacts
          path: |
            logs
      - name: Teardown back-to-back licensed distribution of ixia-c
        run: |
          ./do.sh topo rm lic
