name: Perf CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Setup docker
        uses: docker-practice/actions-setup-docker@master
      - name: Deploy back-to-back licensed distribution of ixia-c
        run: |
          GITHUB_USER=${{ secrets.ENV_GITHUB_USER }} GITHUB_PAT=${{ secrets.ENV_GITHUB_PAT }} ./do.sh topo new lic
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"
      - name: Run go tests
        run: |
          ./do.sh pregotest
          OTG_ITERATIONS=2 ./do.sh gotest -tags=perf
      - name: Get container logs
        run: |
          ./do.sh topo logs lic
      - name: Archive logs
        uses: actions/upload-artifact@v2
        with:
          name: generated-artifacts
          path: |
            logs
      - name: Teardown back-to-back licensed distribution of ixia-c
        run: |
          ./do.sh topo rm lic
